/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-background": "#1c1c19",
        "secondary-container": "#ffc5b0",
        "on-tertiary-fixed": "#341107",
        "secondary-fixed": "#ffdbcf",
        "primary-fixed": "#ffdbd1",
        "surface-dim": "#dcdad5",
        "tertiary": "#814f41",
        "on-secondary-container": "#7a4f3f",
        "error": "#ba1a1a",
        "primary": "#894b39",
        "on-primary-fixed-variant": "#6f3726",
        "on-secondary": "#ffffff",
        "tertiary-fixed-dim": "#f9b7a5",
        "surface-variant": "#e5e2dd",
        "on-tertiary-container": "#fffbff",
        "on-primary": "#ffffff",
        "on-primary-fixed": "#380d02",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f3f0eb",
        "surface-tint": "#8c4d3b",
        "outline-variant": "#d8c2bc",
        "background": "#fcf9f4",
        "secondary-fixed-dim": "#f3baa5",
        "surface-container": "#f0ede9",
        "tertiary-fixed": "#ffdbd1",
        "primary-container": "#a6634f",
        "surface-container-lowest": "#ffffff",
        "on-secondary-fixed": "#311307",
        "surface-bright": "#fcf9f4",
        "on-surface": "#1c1c19",
        "inverse-surface": "#31302d",
        "surface-container-high": "#ebe8e3",
        "surface-container-low": "#f6f3ee",
        "tertiary-container": "#9d6758",
        "on-error": "#ffffff",
        "outline": "#86736e",
        "surface": "#fcf9f4",
        "primary-fixed-dim": "#ffb59f",
        "on-secondary-fixed-variant": "#643d2e",
        "inverse-primary": "#ffb59f",
        "on-primary-container": "#fffbff",
        "on-surface-variant": "#53433f",
        "secondary": "#7f5443",
        "on-error-container": "#93000a",
        "surface-container-highest": "#e5e2dd",
        "on-tertiary-fixed-variant": "#693a2e",
        "on-tertiary": "#ffffff",
        "terracota": "#C27A65"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1.5rem",
        "full": "9999px"
      },
      spacing: {
        "margin-mobile": "16px",
        "container-max-width": "1280px",
        "gutter": "24px",
        "section-gap": "120px",
        "element-gap": "24px",
        "margin-desktop": "64px"
      },
      fontFamily: {
        "display-lg": ["Plus Jakarta Sans"],
        "body-md": ["Manrope"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "display-lg-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Manrope"],
        "label-md": ["Manrope"]
      },
      fontSize: {
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md": ["32px", { "lineHeight": "40px", "fontWeight": "600" }],
        "headline-sm": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "display-lg-mobile": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "label-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.05em", "fontWeight": "600" }]
      }
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
    require("@tailwindcss/container-queries"),
  ],
}
